require "spec"
require "json"
require "http/client"

require "../src/version"
require "../src/process_port"
require "../src/home_port"
require "../src/shell_port"
require "../src/llm/types"
require "../src/llm/token_counter"
require "../src/llm/http_transport"
require "../src/llm/provider"
require "../src/llm/openai_chat_provider"
require "../src/llm/moonshot_provider"
require "../src/llm/zai_provider"
require "../src/llm/ollama_provider"
require "../src/llm/lmstudio_provider"
require "../src/llm/deepseek_provider"
require "../src/llm/groq_provider"
require "../src/llm/openrouter_provider"
require "../src/llm/xai_provider"
require "../src/llm/cerebras_provider"
require "../src/llm/fireworks_provider"
require "../src/llm/together_provider"
require "../src/llm/mock_provider"
require "../src/tools/tool"
require "../src/tools/registry"
require "../src/tools/line_endings"
require "../src/tools/path_access"
require "../src/tools/sensitive"
require "../src/tools/run_rg"
require "../src/tools/bash"
require "../src/tools/read"
require "../src/tools/write"
require "../src/tools/edit"
require "../src/tools/glob"
require "../src/tools/grep"
require "../src/tools/todo_list"
require "../src/tools/agent_swarm"
require "../src/tools/agent"
require "../src/tools/ask_user_question"
require "../src/tools/fetch_url"
require "../src/tools/web_search"
require "../src/tools/skill"
require "../src/tools/plan_mode"
require "../src/tools/goal"
require "../src/tools/task"
require "../src/tools/cron"
require "../src/tools/read_media"
require "../src/tools/select_tools"
require "../src/mcp/types"
require "../src/mcp/tool_naming"
require "../src/mcp/transport"
require "../src/mcp/jsonrpc"
require "../src/mcp/config"
require "../src/mcp/client"
require "../src/mcp/proxy_tool"
require "../src/mcp/manager"
require "../src/mcp/http_transport"
require "../src/mcp/oauth"
require "../src/context/memory"
require "../src/context/budget"
require "../src/context/undo"
require "../src/context/overflow"
require "../src/context/compaction"
require "../src/profiled_memory"
require "../src/permission/manager"
require "../src/permission/danger"
require "../src/permission/policies"
require "../src/loop/events"
require "../src/loop/abort"
require "../src/loop/dedup"
require "../src/loop/tool_batch"
require "../src/loop/agent"
require "../src/loop/subagent_registry"
require "../src/loop/subagent_agent_runner"
require "../src/loop/subagent_swarm_runner"
require "../src/prompt/template"
require "../src/prompt/agents_md"
require "../src/prompt/system_prompt"
require "../src/session/store"
require "../src/session/index"
require "../src/session/lifecycle"
require "../src/session/cleanup"
require "../src/tui/theme"
require "../src/tui/terminal"
require "../src/tui/char_width"
require "../src/tui/markdown"
require "../src/tui/input_wait"
require "../src/tui/input"
require "../src/tui/component"
require "../src/tui/text"
require "../src/tui/spinner"
require "../src/tui/agent_status"
require "../src/tui/editor"
require "../src/tui/fuzzy"
require "../src/tui/select_list"
require "../src/tui/help_panel"
require "../src/tui/commands"
require "../src/tui/question_dialog"
require "../src/tui/plan_review_dialog"
require "../src/tui/undo_dialog"
require "../src/tui/tasks_browser"
require "../src/tui/setup_controller"
require "../src/tui/command_controller"
require "../src/tui/app_models"
require "../src/transcription/presence"
require "../src/transcription/client"
require "../src/tui/telemetry"
require "../src/tui/event_controller"
require "../src/tui/input_controller"
require "../src/tui/turn_controller"
require "../src/tui/render_controller"
require "../src/tui/message_renderer"
require "../src/tui/ui_panels"
require "../src/tui/voice_controller"
require "../src/tui/terminal_port"
require "../src/tui/terminal_mock"
require "../src/tui/ansi_terminal_port"
require "../src/tui/log_zone"
require "../src/tui/active_zone"
require "../src/tui/zones"
require "../src/tui/app"
require "../src/tui/usage_panel"
require "../src/setup/wizard"
require "../src/notify/config"
require "../src/notify/status"
require "../src/notify/terminal"
require "../src/notify/player"
require "../src/notify/webhook"
require "../src/notify/dispatcher"
require "../src/config/config"
require "../src/tips/tips"
require "../src/i18n/i18n"
require "../src/hooks/engine"
require "../src/plugin/types"
require "../src/plugin/store"
require "../src/plugin/source"
require "../src/plugin/manifest"
require "../src/plugin/commands"
require "../src/plugin/manager"

# Initialize i18n so specs that exercise translated strings resolve keys
# instead of getting the raw key back.
H2code::I18n.init("en")

# Create a temp directory and yield it, cleaning up after the block. Used by
# plugin and other specs that need an isolated filesystem.
def with_tmpdir(&)
  dir = File.join(Dir.tempdir, "h2code-spec-#{Random::Secure.hex(6)}")
  Dir.mkdir_p(dir)
  begin
    yield dir
  ensure
    FileUtils.rm_r(dir) if Dir.exists?(dir)
  end
end
